### ISSUE TITLE
Align Flow JVM SDK with latest Access API changes

### ISSUE THREAD

**Issue by lealobanov** [onflow/flow-jvm-sdk#115]
This issue closely follows this epic in the Flow Go SDK: https://github.com/onflow/flow-go-sdk/issues/735

### **Differences with Protobuf**
Below 9 issues summarize differences with protobuf identified in: https://github.com/onflow/flow-go-sdk/issues/736
```[tasklist]
### Tasks
- [ ] https://github.com/onflow/flow-jvm-sdk/issues/114
- [ ] https://github.com/onflow/flow-jvm-sdk/issues/113
- [ ] https://github.com/onflow/flow-jvm-sdk/issues/112
- [ ] https://github.com/onflow/flow-jvm-sdk/issues/111
- [ ] https://github.com/onflow/flow-jvm-sdk/issues/110
- [ ] https://github.com/onflow/flow-jvm-sdk/issues/109
- [ ] https://github.com/onflow/flow-jvm-sdk/issues/108
- [ ] https://github.com/onflow/flow-jvm-sdk/issues/107
- [ ] https://github.com/onflow/flow-jvm-sdk/issues/106
```

### **New Access API Endpoints**
```[tasklist]
### Tasks
- [ ] https://github.com/onflow/flow-jvm-sdk/issues/123
- [ ] https://github.com/onflow/flow-jvm-sdk/issues/124
- [ ] https://github.com/onflow/flow-jvm-sdk/issues/125
- [ ] https://github.com/onflow/flow-jvm-sdk/issues/126
- [ ] https://github.com/onflow/flow-jvm-sdk/issues/127
- [ ] https://github.com/onflow/flow-jvm-sdk/issues/128
- [ ] https://github.com/onflow/flow-jvm-sdk/issues/129
- [ ] https://github.com/onflow/flow-jvm-sdk/issues/130
- [ ] https://github.com/onflow/flow-jvm-sdk/issues/131
- [ ] https://github.com/onflow/flow-jvm-sdk/issues/132
```
